services:
    api_bridge.simple_client:
        class: 'Bigoen\ApiBridge\HttpClient\SimpleClient'
        arguments:
            $httpClient: '@http_client'

    api_bridge.api_platform.jsonld_client:
        class: 'Bigoen\ApiBridge\Bridge\ApiPlatform\HttpClient\JsonldClient'
        arguments:
            $httpClient: '@http_client'
